export const PROJECTS = [
  {
    id: 1,
    name: "UI Design System",
    description: "Design and build a comprehensive UI component library",
    priority: "high",
    progress: 67,
    dueDate: "May 24, 2025",
    category: "Design",
    categoryColor: "#ef4444",
    categoryBg: "#fef2f2",
    icon: "🎨",
    iconBg: "linear-gradient(135deg, #fce7f3, #fbcfe8)",
    iconColor: "#ec4899",
    borderColor: "#ef4444",
    progressColor: "#ef4444",
    avatars: [
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
      "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
    ],
    extra: 3,
    lucideIcon: "Layers",
  },
  {
    id: 2,
    name: "Backend Development",
    description: "Build REST APIs and database integration for the platform",
    priority: "medium",
    progress: 38,
    dueDate: "Jun 10, 2025",
    category: "Development",
    categoryColor: "#f97316",
    categoryBg: "#fff7ed",
    icon: "⚙️",
    iconBg: "linear-gradient(135deg, #ffedd5, #fed7aa)",
    iconColor: "#ea580c",
    borderColor: "#f97316",
    progressColor: "#f97316",
    avatars: [
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
    ],
    extra: 2,
    lucideIcon: "Code2",
  },
  {
    id: 3,
    name: "Mobile Application",
    description:
      "Develop cross-platform mobile application for iOS and Android",
    priority: "low",
    progress: 24,
    dueDate: "Jun 28, 2025",
    category: "Mobile",
    categoryColor: "#22c55e",
    categoryBg: "#f0fdf4",
    icon: "📱",
    iconBg: "linear-gradient(135deg, #dcfce7, #bbf7d0)",
    iconColor: "#16a34a",
    borderColor: "#22c55e",
    progressColor: "#22c55e",
    avatars: [
      "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
    ],
    extra: 1,
    lucideIcon: "Smartphone",
  },
  {
    id: 4,
    name: "Marketing Website",
    description: "Create and launch the new marketing website 🚀",
    priority: "high",
    progress: 81,
    dueDate: "May 15, 2025",
    category: "Marketing",
    categoryColor: "#8b5cf6",
    categoryBg: "#f5f3ff",
    icon: "🌐",
    iconBg: "linear-gradient(135deg, #ede9fe, #ddd6fe)",
    iconColor: "#7c3aed",
    borderColor: "#ef4444",
    progressColor: "#7c3aed",
    avatars: [
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
    ],
    extra: 2,
    lucideIcon: "Globe",
  },
  {
    id: 5,
    name: "Team Dashboard",
    description: "Internal analytics dashboard for team performance 📊",
    priority: "medium",
    progress: 53,
    dueDate: "Jun 05, 2025",
    category: "Internal",
    categoryColor: "#3b82f6",
    categoryBg: "#eff6ff",
    icon: "📊",
    iconBg: "linear-gradient(135deg, #dbeafe, #bfdbfe)",
    iconColor: "#2563eb",
    borderColor: "#f97316",
    progressColor: "#3b82f6",
    avatars: [
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
      "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
    ],
    extra: 3,
    lucideIcon: "BarChart3",
  },
  {
    id: 6,
    name: "API Integration",
    description: "Third-party API integration and testing 🔗",
    priority: "low",
    progress: 12,
    dueDate: "Jul 12, 2025",
    category: "Integration",
    categoryColor: "#f43f5e",
    categoryBg: "#fff1f2",
    icon: "🔌",
    iconBg: "linear-gradient(135deg, #ffe4e6, #fecdd3)",
    iconColor: "#e11d48",
    borderColor: "#22c55e",
    progressColor: "#f43f5e",
    avatars: [
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
    ],
    extra: 1,
    lucideIcon: "Plug",
  },
];

/* ─── Per-project Kanban tasks ─── */
const AVATARS = {
  a1: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
  a2: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
  a3: "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
  a4: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1",
};

const PRIORITY_LABELS = { high: "High", medium: "Medium", low: "Low" };

function t(
  id,
  title,
  description,
  status,
  priority,
  assignees,
  tags,
  dueDate,
  dueLabel,
) {
  return {
    id,
    title,
    description,
    status,
    priority,
    priorityLabel: PRIORITY_LABELS[priority],
    assignees: assignees.map((k) => AVATARS[k]),
    tags,
    dueDate,
    dueLabel,
  };
}

export const PROJECT_TASKS = {
  1: [
    t(
      101,
      "Design system tokens",
      "Define color, spacing, and typography tokens",
      "todo",
      "high",
      ["a1", "a2"],
      ["Design", "Tokens"],
      "2025-05-28",
      "In 4 days",
    ),
    t(
      102,
      "Button component variants",
      "Create primary, secondary, ghost button styles",
      "todo",
      "medium",
      ["a3"],
      ["Components"],
      "2025-05-30",
      "In 6 days",
    ),
    t(
      103,
      "Card component library",
      "Build reusable card components with variants",
      "in-progress",
      "high",
      ["a1", "a4"],
      ["Components", "Cards"],
      "2025-05-24",
      "Today",
    ),
    t(
      104,
      "Form input styles",
      "Style all form inputs with focus and error states",
      "in-progress",
      "medium",
      ["a2"],
      ["Forms"],
      "2025-05-26",
      "In 2 days",
    ),
    t(
      105,
      "Icon set review",
      "Review and approve the new icon set",
      "review",
      "low",
      ["a3", "a1"],
      ["Icons", "Review"],
      "2025-05-22",
      "Yesterday",
    ),
    t(
      106,
      "Typography scale",
      "Finalize the typography scale and line heights",
      "completed",
      "high",
      ["a1", "a2"],
      ["Typography"],
      "2025-05-18",
      "Completed",
    ),
    t(
      107,
      "Color palette audit",
      "Audit existing colors and map to new tokens",
      "completed",
      "medium",
      ["a4"],
      ["Design", "Audit"],
      "2025-05-15",
      "Completed",
    ),
  ],
  2: [
    t(
      201,
      "Set up Express server",
      "Initialize Express with middleware and routing",
      "todo",
      "high",
      ["a2", "a4"],
      ["Backend", "Setup"],
      "2025-05-29",
      "In 5 days",
    ),
    t(
      202,
      "User authentication API",
      "Build register, login, and refresh token endpoints",
      "todo",
      "high",
      ["a1"],
      ["Auth", "API"],
      "2025-06-01",
      "In 8 days",
    ),
    t(
      203,
      "Database schema design",
      "Design PostgreSQL schema for users and projects",
      "in-progress",
      "high",
      ["a2"],
      ["Database", "Schema"],
      "2025-05-24",
      "Today",
    ),
    t(
      204,
      "REST endpoint for tasks",
      "CRUD endpoints for task management",
      "in-progress",
      "medium",
      ["a4", "a3"],
      ["API", "Tasks"],
      "2025-05-27",
      "In 3 days",
    ),
    t(
      205,
      "Rate limiting middleware",
      "Add rate limiting to public API endpoints",
      "review",
      "low",
      ["a1"],
      ["Security", "Middleware"],
      "2025-05-23",
      "Yesterday",
    ),
    t(
      206,
      "API error handling",
      "Standardized error response format",
      "completed",
      "medium",
      ["a2"],
      ["API", "Errors"],
      "2025-05-19",
      "Completed",
    ),
  ],
  3: [
    t(
      301,
      "iOS navigation flow",
      "Implement tab bar and navigation stack for iOS",
      "todo",
      "high",
      ["a3", "a1"],
      ["iOS", "Navigation"],
      "2025-06-02",
      "In 9 days",
    ),
    t(
      302,
      "Android theme适配",
      "Apply Material You styling for Android",
      "todo",
      "medium",
      ["a4"],
      ["Android", "Theme"],
      "2025-06-05",
      "In 12 days",
    ),
    t(
      303,
      "Push notification setup",
      "Integrate Firebase Cloud Messaging",
      "in-progress",
      "high",
      ["a2", "a3"],
      ["Notifications", "Firebase"],
      "2025-05-25",
      "Tomorrow",
    ),
    t(
      304,
      "Offline sync logic",
      "Queue actions when offline and sync on reconnect",
      "in-progress",
      "high",
      ["a1"],
      ["Offline", "Sync"],
      "2025-05-28",
      "In 4 days",
    ),
    t(
      305,
      "Splash screen design",
      "Review animated splash screen implementation",
      "review",
      "low",
      ["a3"],
      ["UI", "Splash"],
      "2025-05-24",
      "Today",
    ),
    t(
      306,
      "App store assets",
      "Prepare screenshots and descriptions for app store",
      "completed",
      "medium",
      ["a4", "a1"],
      ["Store", "Assets"],
      "2025-05-20",
      "Completed",
    ),
  ],
  4: [
    t(
      401,
      "Landing page hero",
      "Design and build the hero section with CTA",
      "todo",
      "high",
      ["a1", "a2"],
      ["Landing", "Hero"],
      "2025-05-22",
      "Yesterday",
    ),
    t(
      402,
      "SEO meta tags",
      "Add Open Graph and Twitter card meta tags",
      "todo",
      "low",
      ["a4"],
      ["SEO"],
      "2025-05-26",
      "In 2 days",
    ),
    t(
      403,
      "Pricing section",
      "Build the pricing comparison table",
      "in-progress",
      "medium",
      ["a3", "a1"],
      ["Landing", "Pricing"],
      "2025-05-24",
      "Today",
    ),
    t(
      404,
      "Blog template",
      "Create the blog post template with MDX",
      "in-progress",
      "medium",
      ["a2"],
      ["Blog", "MDX"],
      "2025-05-29",
      "In 5 days",
    ),
    t(
      405,
      "Analytics integration",
      "Review GA4 and Hotjar event tracking",
      "review",
      "low",
      ["a4"],
      ["Analytics"],
      "2025-05-23",
      "Yesterday",
    ),
    t(
      406,
      "Deploy to Vercel",
      "Set up CI/CD pipeline and deploy",
      "completed",
      "high",
      ["a1", "a2"],
      ["Deploy", "CI/CD"],
      "2025-05-14",
      "Completed",
    ),
    t(
      407,
      "Responsive navigation",
      "Mobile-first responsive header and footer",
      "completed",
      "medium",
      ["a3"],
      ["Responsive", "Nav"],
      "2025-05-12",
      "Completed",
    ),
  ],
  5: [
    t(
      501,
      "Chart component library",
      "Build reusable chart components with Recharts",
      "todo",
      "high",
      ["a2", "a4"],
      ["Charts", "Components"],
      "2025-06-03",
      "In 10 days",
    ),
    t(
      502,
      "Data fetching layer",
      "Set up SWR for data fetching and caching",
      "todo",
      "medium",
      ["a1"],
      ["Data", "SWR"],
      "2025-06-06",
      "In 13 days",
    ),
    t(
      503,
      "Filter sidebar",
      "Build the filter sidebar with date range and team",
      "in-progress",
      "high",
      ["a3", "a1"],
      ["UI", "Filters"],
      "2025-05-25",
      "Tomorrow",
    ),
    t(
      504,
      "KPI cards row",
      "Animated KPI summary cards with sparklines",
      "in-progress",
      "medium",
      ["a4"],
      ["UI", "KPI"],
      "2025-05-27",
      "In 3 days",
    ),
    t(
      505,
      "Export to CSV",
      "Review the CSV export feature",
      "review",
      "low",
      ["a2"],
      ["Export"],
      "2025-05-24",
      "Today",
    ),
    t(
      506,
      "Dark mode support",
      "Add dark mode toggle and theme variables",
      "completed",
      "high",
      ["a1", "a3"],
      ["Theme", "Dark Mode"],
      "2025-05-18",
      "Completed",
    ),
  ],
  6: [
    t(
      601,
      "Stripe webhook handler",
      "Handle Stripe webhooks for subscription events",
      "todo",
      "high",
      ["a2"],
      ["Stripe", "Webhooks"],
      "2025-06-08",
      "In 15 days",
    ),
    t(
      602,
      "Slack notification integration",
      "Post updates to Slack channels via webhook",
      "todo",
      "low",
      ["a4"],
      ["Slack", "Integration"],
      "2025-06-10",
      "In 17 days",
    ),
    t(
      603,
      "OAuth 2.0 flow",
      "Implement Google and GitHub OAuth sign-in",
      "in-progress",
      "high",
      ["a1", "a2"],
      ["Auth", "OAuth"],
      "2025-05-26",
      "In 2 days",
    ),
    t(
      604,
      "Webhook retry logic",
      "Add exponential backoff retry for failed webhooks",
      "in-progress",
      "medium",
      ["a3"],
      ["Webhooks", "Retry"],
      "2025-05-28",
      "In 4 days",
    ),
    t(
      605,
      "API key management",
      "Review the API key generation and rotation flow",
      "review",
      "medium",
      ["a4", "a1"],
      ["Security", "API Keys"],
      "2025-05-25",
      "Tomorrow",
    ),
    t(
      606,
      "Integration tests",
      "Write end-to-end tests for all third-party APIs",
      "completed",
      "high",
      ["a2"],
      ["Testing", "E2E"],
      "2025-05-16",
      "Completed",
    ),
  ],
};

export const PRIORITY_COLORS = {
  high: {
    dot: "#ef4444",
    label: "High Priority",
    text: "text-red-500",
    bg: "bg-red-50 dark:bg-red-900/20",
  },
  medium: {
    dot: "#f97316",
    label: "Medium Priority",
    text: "text-orange-500",
    bg: "bg-orange-50 dark:bg-orange-900/20",
  },
  low: {
    dot: "#22c55e",
    label: "Low Priority",
    text: "text-green-500",
    bg: "bg-green-50 dark:bg-green-900/20",
  },
};
