export const PROJECTS = [
  {
    id: 1,
    name: 'UI Design System',
    description: 'Design and build a comprehensive UI component library',
    priority: 'high',
    progress: 67,
    dueDate: 'May 24, 2025',
    category: 'Design',
    categoryColor: '#ef4444',
    categoryBg: '#fef2f2',
    icon: '🎨',
    iconBg: 'linear-gradient(135deg, #fce7f3, #fbcfe8)',
    iconColor: '#ec4899',
    borderColor: '#ef4444',
    progressColor: '#ef4444',
    avatars: [
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 3,
    lucideIcon: 'Layers',
  },
  {
    id: 2,
    name: 'Backend Development',
    description: 'Build REST APIs and database integration for the platform',
    priority: 'medium',
    progress: 38,
    dueDate: 'Jun 10, 2025',
    category: 'Development',
    categoryColor: '#f97316',
    categoryBg: '#fff7ed',
    icon: '⚙️',
    iconBg: 'linear-gradient(135deg, #ffedd5, #fed7aa)',
    iconColor: '#ea580c',
    borderColor: '#f97316',
    progressColor: '#f97316',
    avatars: [
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 2,
    lucideIcon: 'Code2',
  },
  {
    id: 3,
    name: 'Mobile Application',
    description: 'Develop cross-platform mobile application for iOS and Android',
    priority: 'low',
    progress: 24,
    dueDate: 'Jun 28, 2025',
    category: 'Mobile',
    categoryColor: '#22c55e',
    categoryBg: '#f0fdf4',
    icon: '📱',
    iconBg: 'linear-gradient(135deg, #dcfce7, #bbf7d0)',
    iconColor: '#16a34a',
    borderColor: '#22c55e',
    progressColor: '#22c55e',
    avatars: [
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 1,
    lucideIcon: 'Smartphone',
  },
  {
    id: 4,
    name: 'Marketing Website',
    description: 'Create and launch the new marketing website 🚀',
    priority: 'high',
    progress: 81,
    dueDate: 'May 15, 2025',
    category: 'Marketing',
    categoryColor: '#8b5cf6',
    categoryBg: '#f5f3ff',
    icon: '🌐',
    iconBg: 'linear-gradient(135deg, #ede9fe, #ddd6fe)',
    iconColor: '#7c3aed',
    borderColor: '#ef4444',
    progressColor: '#7c3aed',
    avatars: [
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 2,
    lucideIcon: 'Globe',
  },
  {
    id: 5,
    name: 'Team Dashboard',
    description: 'Internal analytics dashboard for team performance 📊',
    priority: 'medium',
    progress: 53,
    dueDate: 'Jun 05, 2025',
    category: 'Internal',
    categoryColor: '#3b82f6',
    categoryBg: '#eff6ff',
    icon: '📊',
    iconBg: 'linear-gradient(135deg, #dbeafe, #bfdbfe)',
    iconColor: '#2563eb',
    borderColor: '#f97316',
    progressColor: '#3b82f6',
    avatars: [
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 3,
    lucideIcon: 'BarChart3',
  },
  {
    id: 6,
    name: 'API Integration',
    description: 'Third-party API integration and testing 🔗',
    priority: 'low',
    progress: 12,
    dueDate: 'Jul 12, 2025',
    category: 'Integration',
    categoryColor: '#f43f5e',
    categoryBg: '#fff1f2',
    icon: '🔌',
    iconBg: 'linear-gradient(135deg, #ffe4e6, #fecdd3)',
    iconColor: '#e11d48',
    borderColor: '#22c55e',
    progressColor: '#f43f5e',
    avatars: [
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 1,
    lucideIcon: 'Plug',
  },
];

export const PRIORITY_COLORS = {
  high:   { dot: '#ef4444', label: 'High Priority',   text: 'text-red-500',    bg: 'bg-red-50 dark:bg-red-900/20' },
  medium: { dot: '#f97316', label: 'Medium Priority', text: 'text-orange-500', bg: 'bg-orange-50 dark:bg-orange-900/20' },
  low:    { dot: '#22c55e', label: 'Low Priority',    text: 'text-green-500',  bg: 'bg-green-50 dark:bg-green-900/20' },
};
