export const TASKS = [
  {
    id: 1,
    name: 'Review design mockups',
    description: 'Review the latest design mockups for the landing page',
    priority: 'high',
    status: 'todo',
    project: 'Design',
    projectColor: '#8b5cf6',
    projectBg: '#f5f3ff',
    dueDate: '2025-05-24',
    dueDateLabel: 'Today',
    dueDateState: 'today',
    comments: 12,
    attachments: 3,
    estimate: '4h',
    completed: false,
    lucideIcon: 'Monitor',
    iconBg: '#fce7f3',
    iconColor: '#ec4899',
    avatars: [
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 2,
  },
  {
    id: 2,
    name: 'Implement authentication',
    description: 'Add JWT authentication and protected routes',
    priority: 'medium',
    status: 'in-progress',
    project: 'Development',
    projectColor: '#3b82f6',
    projectBg: '#eff6ff',
    dueDate: '2025-05-26',
    dueDateLabel: 'In 2 days',
    dueDateState: 'future',
    comments: 8,
    attachments: 1,
    estimate: '6h',
    completed: false,
    lucideIcon: 'Code2',
    iconBg: '#ffedd5',
    iconColor: '#ea580c',
    avatars: [
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 1,
  },
  {
    id: 3,
    name: 'Write unit tests',
    description: 'Write unit tests for the authentication modules',
    priority: 'medium',
    status: 'review',
    project: 'Development',
    projectColor: '#3b82f6',
    projectBg: '#eff6ff',
    dueDate: '2025-05-28',
    dueDateLabel: 'In 4 days',
    dueDateState: 'future',
    comments: 5,
    attachments: 2,
    estimate: '3h',
    completed: false,
    lucideIcon: 'FileText',
    iconBg: '#ede9fe',
    iconColor: '#7c3aed',
    avatars: [
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 1,
  },
  {
    id: 4,
    name: 'Deploy to production',
    description: 'Deploy the application to production environment',
    priority: 'high',
    status: 'completed',
    project: 'DevOps',
    projectColor: '#22c55e',
    projectBg: '#f0fdf4',
    dueDate: '2025-05-20',
    dueDateLabel: 'Completed',
    dueDateState: 'completed',
    comments: 3,
    attachments: 1,
    estimate: '2h',
    completed: true,
    lucideIcon: 'Rocket',
    iconBg: '#dcfce7',
    iconColor: '#16a34a',
    avatars: [
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 0,
  },
  {
    id: 5,
    name: 'Update API documentation',
    description: 'Document all REST endpoints in the API specification',
    priority: 'low',
    status: 'todo',
    project: 'Design',
    projectColor: '#8b5cf6',
    projectBg: '#f5f3ff',
    dueDate: '2025-06-01',
    dueDateLabel: 'In 8 days',
    dueDateState: 'future',
    comments: 2,
    attachments: 4,
    estimate: '5h',
    completed: false,
    lucideIcon: 'BookOpen',
    iconBg: '#dbeafe',
    iconColor: '#2563eb',
    avatars: [
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 0,
  },
  {
    id: 6,
    name: 'Design onboarding flow',
    description: 'Create wireframes and prototypes for the user onboarding experience',
    priority: 'high',
    status: 'todo',
    project: 'Design',
    projectColor: '#8b5cf6',
    projectBg: '#f5f3ff',
    dueDate: '2025-05-22',
    dueDateLabel: 'Yesterday',
    dueDateState: 'overdue',
    comments: 6,
    attachments: 8,
    estimate: '8h',
    completed: false,
    lucideIcon: 'Layers',
    iconBg: '#fce7f3',
    iconColor: '#db2777',
    avatars: [
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 3,
  },
  {
    id: 7,
    name: 'Fix mobile navigation bug',
    description: 'The hamburger menu is not responsive on iOS Safari',
    priority: 'high',
    status: 'in-progress',
    project: 'Development',
    projectColor: '#3b82f6',
    projectBg: '#eff6ff',
    dueDate: '2025-05-25',
    dueDateLabel: 'Tomorrow',
    dueDateState: 'today',
    comments: 4,
    attachments: 2,
    estimate: '2h',
    completed: false,
    lucideIcon: 'Smartphone',
    iconBg: '#ffedd5',
    iconColor: '#f97316',
    avatars: [
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=60&h=60&dpr=1',
    ],
    extra: 0,
  },
];

export const STATUS_CONFIG = {
  'todo':        { label: 'To Do',       color: '#6b7280', bg: '#f9fafb', darkBg: 'rgba(107,114,128,.15)', border: '#e5e7eb', icon: 'Circle' },
  'in-progress': { label: 'In Progress', color: '#3b82f6', bg: '#eff6ff', darkBg: 'rgba(59,130,246,.15)',  border: '#bfdbfe', icon: 'CircleDot' },
  'review':      { label: 'Review',      color: '#8b5cf6', bg: '#f5f3ff', darkBg: 'rgba(139,92,246,.15)',  border: '#ddd6fe', icon: 'CircleDashed' },
  'completed':   { label: 'Completed',   color: '#22c55e', bg: '#f0fdf4', darkBg: 'rgba(34,197,94,.15)',   border: '#bbf7d0', icon: 'CheckCircle2' },
};

export const PRIORITY_CONFIG = {
  high:   { label: 'High',   color: '#ef4444', strip: '#ef4444' },
  medium: { label: 'Medium', color: '#f97316', strip: '#f97316' },
  low:    { label: 'Low',    color: '#22c55e', strip: '#22c55e' },
};
